//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Faculties = new HashSet<Faculty>();
            this.Projects = new HashSet<Project>();
        }
    
        public int Id { get; set; }
        public string DepartId { get; set; }
        public string Name { get; set; }
        public int CampusId { get; set; }

        public virtual Campus Campu { get; set; }
        public virtual ICollection<Faculty> Faculties { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
