//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standard
    {
        public int Id { get; set; }
        public string StandardName { get; set; }
        public string StandardId { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
