//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Accounts = new HashSet<Account>();
            this.Books = new HashSet<Book>();
        }
    
        public int Id { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string StandardId { get; set; }
        public int CampusId { get; set; }
    
        public virtual Standard Standard { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Program Program { get; set; }
        public virtual Campus Campu { get; set; }
        public virtual Car Car { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Book> Books { get; set; }
    }
}
